music.changeTempoBy(139)
music.playTone(297, music.beat(BeatFraction.Whole))
music.playTone(297, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(297, music.beat(BeatFraction.Whole))
music.playTone(297, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(389, music.beat(BeatFraction.Half))
music.playTone(389, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(389, music.beat(BeatFraction.Whole))
music.playTone(389, music.beat(BeatFraction.Half))
music.playTone(221, music.beat(BeatFraction.Whole))
music.playTone(246, music.beat(BeatFraction.Whole))
music.playTone(264, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(385, music.beat(BeatFraction.Whole))
music.playTone(246, music.beat(BeatFraction.Whole))
music.playTone(290, music.beat(BeatFraction.Whole))
music.playTone(390, music.beat(BeatFraction.Whole))
music.playTone(236, music.beat(BeatFraction.Whole))
music.playTone(290, music.beat(BeatFraction.Whole))
music.playTone(390, music.beat(BeatFraction.Whole))
music.playTone(220, music.beat(BeatFraction.Whole))
